# Default values for sftpserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  repository: zensum/sftpserver
  tag: stable
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  externalPort: 22
  internalPort: 2222
env:
  projectId: "example"
  storageBucket: "example"
  sftpUsername: "example"
config: |
  [auth]
    authorized_keys_path = "/etc/config/authorized_keys"
  [sftp]
    listen = "0.0.0.0"
    host_key_path = "/etc/host-key/id_rsa"
resources: {}
